version: "3.8"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=your_token_here
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
